services:
  - type: web
    name: nainamain
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - client/**/*
        - server/**/*
        - shared/**/*
        - package.json
        - tsconfig*.json
        - vite.config.ts 