services:
  - type: web
    name: nainaland
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: cd dist && node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This will be set manually in Render dashboard
    buildFilter:
      paths:
        - client/**/*
        - server/**/*
        - shared/**/*
        - package.json
        - tsconfig*.json
        - vite.config.ts 