services:
  - type: web
    name: nainaland
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: cd dist && node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/health
    buildFilter:
      paths:
      - client/**/*
      - server/**/*
      - shared/**/*
      - package.json
      - package-lock.json
      - tsconfig*.json
      - vite.config.ts
    autoDeploy: true 